"""
env/models.py — Data models for AMR-Steward.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, ConfigDict, Field, field_validator


# ---------------------------------------------------------------------------
# Minimal base classes (previously from openenv-core)
# ---------------------------------------------------------------------------

class Action(BaseModel):
    """Base action."""
    pass


class Observation(BaseModel):
    """Base observation — carries done/reward/metadata."""
    done: bool = False
    reward: Optional[float] = None
    metadata: Optional[Dict[str, Any]] = None


class State(BaseModel):
    """Base episode state."""
    model_config = ConfigDict(extra="allow")
    episode_id: str = ""
    step_count: int = 0




@dataclass
class PatientCase:
    """A single patient episode. Generated by data/patient_generator.py."""
    age: int
    sex: str                          
    infection_site: str                
    organism: str                     
    creatinine_clearance: float        
    allergies: list[str]               
    antibiogram: dict[str, float]      
    phenotype: str                    
    curriculum_level: int             




class AMRAction(Action):
    """
    Action the agent emits each step.

    Two action types:
      - INVESTIGATE: call a diagnostic tool (consumes 1 budget)
      - COMMIT:      finalise prescription (terminates episode, computes reward)
    """

    action_type: str = Field(
        ...,
        description="'INVESTIGATE' to call a diagnostic tool, 'COMMIT' to finalise prescription.",
        examples=["INVESTIGATE", "COMMIT"],
    )
    tool_name: Optional[str] = Field(
        default=None,
        description="Required when action_type='INVESTIGATE'. One of: "
                    "interpret_resistance | check_guideline | assess_patient_factors.",
    )
    tool_arg: Optional[str] = Field(
        default=None,
        description="Argument for the tool — e.g. drug name or syndrome name.",
    )
    prescription: Optional[Dict[str, Any]] = Field(
        default=None,
        description="Required when action_type='COMMIT'. Keys: drug, dose, duration, justification.",
    )

    @field_validator("action_type")
    @classmethod
    def _validate_action_type(cls, v: str) -> str:
        allowed = {"INVESTIGATE", "COMMIT"}
        if v not in allowed:
            raise ValueError(f"action_type must be one of {allowed}, got '{v}'")
        return v

    @field_validator("tool_name")
    @classmethod
    def _validate_tool_name(cls, v: Optional[str]) -> Optional[str]:
        if v is None:
            return v
        allowed = {"interpret_resistance", "check_guideline", "assess_patient_factors"}
        if v not in allowed:
            raise ValueError(f"tool_name must be one of {allowed}, got '{v}'")
        return v



class AMRObservation(Observation):
    """
    What the agent sees after each reset() / step().

    Inherits `done`, `reward`, and `metadata` from the OpenEnv base.
    `metadata` carries the per-component reward breakdown on COMMIT.
    """

    patient_text: str = Field(
        default="",
        description="Plain-English patient description (age/sex/site/organism/CrCl/allergies/antibiogram).",
    )
    tool_results: List[str] = Field(
        default_factory=list,
        description="Results from INVESTIGATE tool calls so far this episode.",
    )
    budget_remaining: int = Field(
        default=5,
        description="Remaining INVESTIGATE budget for this episode.",
    )
    world_model_rankings: str = Field(
        default="",
        description="JEPA world-model predicted-information-gain rankings for the next tool call.",
    )

    def to_text(self) -> str:
        """Render the full observation as a single string the LLM sees."""
        parts = [self.patient_text]
        if self.tool_results:
            parts.append("Tool results so far:")
            parts.extend(f"  - {r}" for r in self.tool_results)
        if self.world_model_rankings:
            parts.append(self.world_model_rankings)
        parts.append(f"Budget remaining: {self.budget_remaining} tool call(s).")
        if self.done:
            parts.append("Episode complete.")
        return "\n".join(parts)




class AMRState(State):
    """
    Internal episode metadata. Inherits `episode_id` and `step_count` from
    OpenEnv's base State (this is what gets returned by GET /state).

    AMR-specific fields are extra (the base class allows it via
    `model_config = ConfigDict(extra='allow')`).
    """

    curriculum_level: int = Field(default=1, description="Curriculum stage (1, 2, or 3).")
    budget_remaining: int = Field(default=5, description="Remaining INVESTIGATE budget.")
    done: bool = Field(default=False, description="Whether the episode has terminated.")
    patient: Optional[Dict[str, Any]] = Field(
        default=None,
        description="Serialised PatientCase for the active episode (debugging only).",
    )
    tool_results: List[str] = Field(default_factory=list)
    called_tools: List[str] = Field(default_factory=list)
    dense_accum: float = Field(default=0.0)
    tool_history: List[Dict[str, Any]] = Field(
        default_factory=list,
        description="Structured log of INVESTIGATE calls: [{tool, arg}, ...]. "
                    "Single source of truth for R5 unique_tool_types — no text parsing.",
    )
    last_reward_breakdown: Optional[Dict[str, Any]] = Field(
        default=None,
        description="Per-component reward breakdown from the last COMMIT.",
    )
